# Generated by Django 3.2.6 on 2021-08-20 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('messages_ok', models.BooleanField(default=True)),
                ('favoret_ads', models.ManyToManyField(to='ads.ads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('center_city', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': True, 'governorate_name__isnull': False, 'region_village__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_center_city', to='user_profile.governorate')),
                ('governorate_name', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': True, 'governorate_name__isnull': True, 'region_village__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_governorate_name', to='user_profile.governorate')),
                ('region_village', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': False, 'governorate_name__isnull': False, 'region_village__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_region_village', to='user_profile.governorate')),
            ],
            options={
                'verbose_name': 'governorate',
                'verbose_name_plural': 'governorate',
            },
        ),
        migrations.CreateModel(
            name='adress_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_description', models.CharField(max_length=120)),
                ('center_city', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': True, 'governorate_name__isnull': False, 'region_village__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cho_center_city', to='user_profile.governorate')),
                ('governorate_name', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': True, 'governorate_name__isnull': True, 'region_village__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cho_governorate_name', to='user_profile.governorate')),
                ('last', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': False, 'governorate_name__isnull': False, 'region_village__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cho_last', to='user_profile.governorate', verbose_name='Last adress')),
                ('region_village', models.ForeignKey(blank=True, limit_choices_to={'center_city__isnull': False, 'governorate_name__isnull': False, 'region_village__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cho_region_village', to='user_profile.governorate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
